export interface Data {
    id: string;
    time: string;
    client: string;
    ticker: string;
    side: "Buy" | "Sell";
    quantity: string;
    product: string;
    price: number;
  }
  
  export const dummyData: Data[] = [
    {
      id: "1",
      time: "09:00:00",
      client: "Alpha Capital",
      ticker: "AAPL",
      side: "Buy",
      quantity: "100",
      product: "Equity",
      price: 172.35,
    },
    {
      id: "2",
      time: "09:05:00",
      client: "Beta Holdings",
      ticker: "GOOGL",
      side: "Sell",
      quantity: "50",
      product: "Equity",
      price: 2845.5,
    },
    {
      id: "3",
      time: "09:10:00",
      client: "Sigma Investments",
      ticker: "TSLA",
      side: "Buy",
      quantity: "25",
      product: "Futures",
      price: 672.1,
    },
    {
      id: "4",
      time: "09:15:00",
      client: "Omega Traders",
      ticker: "MSFT",
      side: "Sell",
      quantity: "75",
      product: "Options",
      price: 309.2,
    },
    {
      id: "5",
      time: "09:20:00",
      client: "Delta Corp",
      ticker: "AMZN",
      side: "Buy",
      quantity: "30",
      product: "Equity",
      price: 3342.88,
    },
    {
      id: "6",
      time: "09:25:00",
      client: "Phoenix Equity",
      ticker: "NFLX",
      side: "Sell",
      quantity: "45",
      product: "Equity",
      price: 505.6,
    },
    {
      id: "7",
      time: "09:30:00",
      client: "Orion Finance",
      ticker: "NVDA",
      side: "Buy",
      quantity: "60",
      product: "Options",
      price: 825.9,
    },
    {
      id: "8",
      time: "09:35:00",
      client: "Zenith Capital",
      ticker: "INTC",
      side: "Sell",
      quantity: "80",
      product: "Futures",
      price: 45.25,
    },
    {
      id: "9",
      time: "09:40:00",
      client: "Astra Wealth",
      ticker: "BABA",
      side: "Buy",
      quantity: "55",
      product: "Equity",
      price: 212.7,
    },
    {
      id: "10",
      time: "09:45:00",
      client: "Nimbus Fund",
      ticker: "UBER",
      side: "Sell",
      quantity: "90",
      product: "Equity",
      price: 47.85,
    },
    {
      id: "11",
      time: "09:50:00",
      client: "Apollo Traders",
      ticker: "LYFT",
      side: "Buy",
      quantity: "35",
      product: "Futures",
      price: 16.95,
    },
    {
      id: "12",
      time: "09:55:00",
      client: "Crescent Global",
      ticker: "BA",
      side: "Sell",
      quantity: "100",
      product: "Options",
      price: 230.1,
    },
    {
      id: "13",
      time: "10:00:00",
      client: "Nova Investments",
      ticker: "SPY",
      side: "Buy",
      quantity: "70",
      product: "Equity",
      price: 439.85,
    },
    {
      id: "14",
      time: "10:05:00",
      client: "Vertex Finance",
      ticker: "AMD",
      side: "Sell",
      quantity: "40",
      product: "Equity",
      price: 121.4,
    },
    {
      id: "15",
      time: "10:10:00",
      client: "Stellar Partners",
      ticker: "FB",
      side: "Buy",
      quantity: "65",
      product: "Futures",
      price: 338.75,
    },
    {
      id: "16",
      time: "10:15:00",
      client: "Nimbus Fund",
      ticker: "CRM",
      side: "Sell",
      quantity: "85",
      product: "Options",
      price: 256,
    },
    {
      id: "17",
      time: "10:20:00",
      client: "Aurora Group",
      ticker: "ZM",
      side: "Buy",
      quantity: "95",
      product: "Equity",
      price: 113.55,
    },
    {
      id: "18",
      time: "10:25:00",
      client: "Eclipse Holdings",
      ticker: "TWTR",
      side: "Sell",
      quantity: "20",
      product: "Equity",
      price: 42.33,
    },
    {
      id: "19",
      time: "10:30:00",
      client: "Quantum Markets",
      ticker: "SNAP",
      side: "Buy",
      quantity: "48",
      product: "Futures",
      price: 9.85,
    },
    {
      id: "20",
      time: "10:35:00",
      client: "Falcon Advisory",
      ticker: "PINS",
      side: "Sell",
      quantity: "77",
      product: "Options",
      price: 27.65,
    },
  ];
  